sudo: required
dist: trusty
language : python3
node_js  :
  - "6.x"

before_install:
    - "sudo ./build/support/pkman install node"
    - "sudo ./build/enviro"
    - "./build/deps"
install : "./build/run"
script : "./build/test"
