sudo: required
dist: trusty
language : python3
node_js:
    - "6"
before_install:
    - "curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -"
    - "./build/support/pkman install node"
    - "./build/run enviro"
    - "./build/run deps"
install : "./build/run build"
script : "./build/run test"
