sudo: required
dist: trusty
before_install:
    - "sudo ./build/support/pkman install node"
    - "sudo ./build/build-run enviro"
    - "./build/build-run deps"
install : "./build/build-run build"
script : "./build/build-run test"
