sudo: required
dist: trusty
language : node_js
node_js:
    - "6"
before_install:
    - "./build/support/pkman install python3"
    - "node --version"
    - "python --version"
    - "./build/run enviro"
    - "./build/run deps"
install : "./build/run build"
script : "./build/run test"
