sudo: required
dist: trusty
language : python3
before_install:
    - "sudo ./build/support/pkman install node"
    - "sudo ./build/run enviro"
    - "./build/run deps"
install : "./build/run build"
script : "./build/run test"
