sudo: required
dist: trusty
language : python3
node_js  :
  - "6.x"

before_install:
    - "sudo ./build/support/pkman install node"
    - "node --version"
install : "./build/install"
script : "./build/run"
