sudo: required
dist: trusty
language : python3
node_js:
    - "4.x"
before_install:
    - "sudo ./build/support/pkman install node"
    - "sudo ./build/run enviro"
    - "sudo ./build/run deps"
install : "./build/run build"
script : "./build/run test"
