sudo: required
dist: trusty
language : node_js
node_js:
    - "6"
before_install:
    - "./build/support/pkman install python3"
    - "node --version"
    - "python --version"
    - "./build/run enviro"
    - "./build/run deps"
    - "sudo wget http://download.gna.org/wkhtmltopdf/0.12/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb"
    - "sudo dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb"
install : "./build/run build"
script : "./build/run test"
